# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 563c9854111787c78c6f0bb4608ff6fc1b477b05ac796c5026c6b99683236e722ccc4d7e2935639467654f5ab437dab4428f048fec6b7658e5451ead80d827f7

test:
  secret_key_base: 06fdc55e7c7181df2661d209925b6a9f6ec8c0a6fb11f4cdfa7491ef67ac59c0c79d61961973d3338bec345c701fb40275dde9423d62911a103040d83429da67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
